services:
  frankenphp:
    container_name: schedtrip_back
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app # For dev only
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mysql
    tty: true
    networks:
      - schedtrip_network
  mysql:
    container_name: schedtrip_db
    image: mysql:8.0
    ports:
      - "3306:3306" # Only for local dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - schedtrip_network
volumes:
  caddy_data:
  caddy_config:
  db_data:

networks:
  schedtrip_network:
    driver: bridge
