services:
  frankenphp:
    container_name: schedtrip
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app # For dev only
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      mysql:
        condition: service_healthy
      mysql_test:
        condition: service_healthy
    tty: true
    networks:
      - schedtrip_network

  mysql:
    container_name: schedtrip_db
    image: mysql:8.0
    ports:
      - "3306:3306" # Only for local dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - schedtrip_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql_test:
    container_name: schedtrip_db_test
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test_root
      MYSQL_DATABASE: schedtrip_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - db_test_data:/var/lib/mysql
    networks:
      - schedtrip_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
  db_data:
  db_test_data:


networks:
  schedtrip_network:
    driver: bridge
